altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  594cd25f-6f9c-44c2-94de-5b9bdd85e467:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-21T08:55:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 08f29a2b-fc89-4a50-9489-437bf2759ce3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-21T09:27:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e344a845-d8d1-4c54-b3c6-5f29247f0246 # fields-assets-bilder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48beb612-8801-4be1-8af6-1229dd615da2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ac0596a0-5f19-43cd-8e59-ec0f38d3840d
        userCondition: null
fs: filesystemBilder
handle: assetsVolumeBilder
name: assets-volume-bilder
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
