columnSuffix: null
handle: fieldRichText
instructions: null
name: Field-rich-text
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 2554616c-98b6-4ba9-964f-2cfc6332f9f3 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
