currLabel: Assets
customIcon: null
enabled: true
handle: assets
icon: image
layout: fe9b1f45-7caf-44a1-832d-524d6866b69b # Default
level: 1
newWindow: false
parent: null
prevLabel: Assets
prevLevel: 1
prevParent: null
prevUrl: assets
sortOrder: 3
type: craft
url: assets
