currLabel: Categories
customIcon: null
enabled: true
handle: categories
icon: sitemap
layout: fe9b1f45-7caf-44a1-832d-524d6866b69b # Default
level: 1
newWindow: false
parent: null
prevLabel: Categories
prevLevel: 1
prevParent: null
prevUrl: categories
sortOrder: 16
type: craft
url: categories
