currLabel: Entries
customIcon: null
enabled: true
handle: entries
icon: newspaper
layout: fe9b1f45-7caf-44a1-832d-524d6866b69b # Default
level: 1
newWindow: false
parent: null
prevLabel: Entries
prevLevel: 1
prevParent: null
prevUrl: entries
sortOrder: 2
type: craft
url: entries
