currLabel: GraphiQL
customIcon: null
enabled: true
handle: graphiql
icon: null
layout: fe9b1f45-7caf-44a1-832d-524d6866b69b # Default
level: 2
newWindow: true
parent: fdfe3f86-2c88-4a57-bfa9-6a91721fa4c3
prevLabel: GraphiQL
prevLevel: 2
prevParent: fdfe3f86-2c88-4a57-bfa9-6a91721fa4c3
prevUrl: graphiql
sortOrder: 7
type: craft
url: graphiql
