currLabel: GraphQL
customIcon: null
enabled: true
handle: graphql
icon: graphql
layout: fe9b1f45-7caf-44a1-832d-524d6866b69b # Default
level: 1
newWindow: false
parent: null
prevLabel: GraphQL
prevLevel: 1
prevParent: null
prevUrl: graphql
sortOrder: 4
type: craft
url: graphql
