currLabel: Schemas
customIcon: null
enabled: true
handle: schemas
icon: null
layout: fe9b1f45-7caf-44a1-832d-524d6866b69b # Default
level: 2
newWindow: false
parent: fdfe3f86-2c88-4a57-bfa9-6a91721fa4c3
prevLabel: Schemas
prevLevel: 2
prevParent: fdfe3f86-2c88-4a57-bfa9-6a91721fa4c3
prevUrl: graphql/schemas
sortOrder: 5
type: craft
url: graphql/schemas
