currLabel: Settings
customIcon: null
enabled: true
handle: settings
icon: gear
layout: fe9b1f45-7caf-44a1-832d-524d6866b69b # Default
level: 1
newWindow: false
parent: null
prevLabel: Settings
prevLevel: 1
prevParent: null
prevUrl: settings
sortOrder: 9
type: craft
url: settings
