currLabel: Utilities
customIcon: null
enabled: true
handle: utilities
icon: wrench
layout: fe9b1f45-7caf-44a1-832d-524d6866b69b # Default
level: 1
newWindow: false
parent: null
prevLabel: Utilities
prevLevel: 1
prevParent: null
prevUrl: utilities
sortOrder: 8
type: craft
url: utilities
