defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: af5c43f4-5cfd-4fb1-862c-861d8b5284f5 # entry-type-home
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fe6fc921-5409-444c-9b05-4746118e8c68: # blomsterform
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
