defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    handle: entryTypeBilderGallery
    name: entry-type-bilder-gallery
    uid: ff9b228c-95c3-43fa-bdeb-3bd54a2a2fce # entry-type-bilder
handle: sectionGalleryPottery
maxAuthors: 1
name: Section-gallery-pottery
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  fe6fc921-5409-444c-9b05-4746118e8c68: # blomsterform
    enabledByDefault: true
    hasUrls: true
    template: pottery/gallery/gallery.twig
    uriFormat: 'section-gallery-pottery/{slug}'
type: channel
